
development:
  adapter: postgresql
  encoding: unicode
  database: taxpax
  pool: 5
  username: Brooke
  password: skyler

test:
  adapter: postgresql
  encoding: unicode
  database: taxpax
  pool: 5
  username: Brooke
  password: skyler
